### ISSUE TITLE
Support new stage Alpha 3 for 4.10.0 in wazuh-security-dashboards-plugin repository

### ISSUE THREAD

**Issue by wazuhci** [wazuh/wazuh-security-dashboards-plugin#132]
## Description

This issue attempts to support a new stage Alpha 3 for 4.10.0 in the wazuh-security-dashboards-plugin repository.

## Tasks

- [x] Ensure changelog is updated for 4.10.0 (if applicable).
- [x] Bump revision for branch 4.10.0 on wazuh-security-dashboards-plugin repository.
  - https://github.com/wazuh/wazuh-security-dashboards-plugin/pull/133
- [x] Create tag v4.10.0-alpha3 from branch 4.10.0 on wazuh-security-dashboards-plugin repository.
- [x] Create and publish a pre-release: https://github.com/wazuh/wazuh-security-dashboards-plugin/releases/tag/v4.10.0-alpha3.

**Comment by asteriscos** [comment]
LGTM :green_circle:
