### ISSUE TITLE
Support new stage Alpha 1 for 4.9.0 in wazuh-security-dashboards-plugin repository

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-security-dashboards-plugin#54]
## Description

This issue attempts to support a new stage Alpha 1 for 4.9.0 in the wazuh-security-dashboards-plugin repository.

## Tasks

- [ ] Ensure changelog is updated for 4.9.0 (if applicable).
- [ ] Bump revision for branch 4.9.0 on wazuh-security-dashboards-plugin repository.
- [ ] Create tag v4.9.0-alpha1 from branch 4.9.0 on wazuh-security-dashboards-plugin repository.
- [ ] Create and publish a pre-release: https://github.com/wazuh/wazuh-security-dashboards-plugin/releases/tag/v4.9.0-alpha1.
