### ISSUE TITLE
Support new stage RC 1 for 4.8.1 in wazuh-security-dashboards-plugin repository

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-security-dashboards-plugin#60]
## Description

This issue attempts to support a new stage RC 1 for 4.8.1 in the wazuh-security-dashboards-plugin repository.

## Tasks

- [ ] Ensure changelog is updated for 4.8.1 (if applicable).
- [ ] Bump revision for branch 4.8.1 on wazuh-security-dashboards-plugin repository.
- [ ] Create tag v4.8.1-rc1 from branch 4.8.1 on wazuh-security-dashboards-plugin repository.
- [ ] Create and publish a pre-release: https://github.com/wazuh/wazuh-security-dashboards-plugin/releases/tag/v4.8.1-rc1.

**Comment by Desvelao** [comment]
I will close the issue because this repository is not used for releases whose version is lower than 4.9.0.
