### ISSUE TITLE
Support new stage RC 2 for 4.9.0 in wazuh-security-dashboards-plugin repository

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-security-dashboards-plugin#88]
## Description

This issue attempts to support a new stage RC 2 for 4.9.0 in the wazuh-security-dashboards-plugin repository.

## Tasks

- [x] Ensure changelog is updated for 4.9.0 (if applicable).
- [x] Bump revision for branch 4.9.0 on wazuh-security-dashboards-plugin repository. https://github.com/wazuh/wazuh-security-dashboards-plugin/pull/89
- [x] Create tag v4.9.0-rc2 from branch 4.9.0 on wazuh-security-dashboards-plugin repository.
- [x] Create and publish a pre-release: https://github.com/wazuh/wazuh-security-dashboards-plugin/releases/tag/v4.9.0-rc2.
